language: cpp
dist: trusty
matrix:
  include:
  - os: linux
    env: PYTHON=3.8
before_install:
- |
  export CXX=g++-4.8 CC=gcc-4.8
  python -m pip install --user virtualenv
  virtualenv -p python${PYTHON:0:1} venv
  source venv/bin/activate
install:
- |
  python -m pip install .
script:
- python tests/test.py
