name: Pip

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-latest]
        python-version: ["3.7", "3.11"]

    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Add requirements
      run: python -m pip install --upgrade wheel setuptools numpy pytest torch

    - name: Build and install
      run: pip install --verbose .

    - name: Import Test
      run: python -c "import mlpfile; import mlpfile.torch"

    - name: Unit Test
      # The unit tests use a recent feature of PyTorch to construct their
      # Jacobian for comparison. So it cannot run on old versions of Python.
      run: pytest tests/test.py
      if: matrix.python-version == '3.11'
